const baseUrl = "https://essexmortgage.com";
const eStatusHomeUrl = "https://essexmortgage.estatusconnect.com";

/** @type {import("./types").BrandConfig} */
const essex = {
  key: "essex",
  appName: "Essex Servicing",
  slug: "essex-servicing-app",
  version: "1.1.2",
  iosBundleIdentifier: "com.essexservicing.app",
  androidPackage: "com.essexservicing.app",
  easProjectId: "ef50d6ef-2f92-4922-b98e-679f61df082c",
  iosBuildNumber: "37",
  androidVersionCode: 4,
  assets: {
    icon: "./assets/brands/essex/icon.png",
    adaptiveIcon: "./assets/brands/essex/adaptive-icon.png",
    splash: "./assets/brands/essex/icon.png",
    favicon: "./assets/brands/essex/favicon.png",
  },
  baseUrl,
  initialUrl: baseUrl,
  paymentUrl: `${baseUrl}/myaccount#quick-actions`,
  paymentTabLabel: "Pay as Guest",
  loginUrl: eStatusHomeUrl,
  loginStrategy: "direct",
  manageUrl: baseUrl,
  manageLoginUrl: eStatusHomeUrl,
  payAsGuestUrl: `${baseUrl}/myaccount#quick-actions`,
  publicHostnames: ["essexmortgage.com", "www.essexmortgage.com"],
  aboutSlug: "the-essex-story",
  aboutUrl: `${baseUrl}/the-essex-story`,
  hardshipUrl: `${baseUrl}/mortgage-assistance`,
  refinanceUrl: `${baseUrl}/refinance`,
  chatUrl: `${baseUrl}/contact`,
  faqUrl: `${baseUrl}/servicing-learning-center`,
  eStatusLoginUrl: `${eStatusHomeUrl}/User/Login`,
  eStatusHomeUrl,
  trackingDomains: [
    "ad.doubleclick.net",
    "googleads.g.doubleclick.net",
    "www.google.com",
    "www.googletagmanager.com",
  ],
  primary: "#3230be",
  secondary: "",
  textColor: "#fff",
  textColorSecondary: "#333",
  iconColor: "#fff",
  borderColor: "#ccc",
  phone: "8888920881",
  email: "CustomerCARE@EssexMortgage.com",
};

module.exports = essex;
